"""users table

Revision ID: 333d753e3980
Revises: f4dc2f95ae1a
Create Date: 2020-04-13 19:25:10.961826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333d753e3980'
down_revision = 'f4dc2f95ae1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('university1', sa.String(length=64), nullable=True),
    sa.Column('university2', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('skill1', sa.String(length=64), nullable=True),
    sa.Column('skill2', sa.String(length=64), nullable=True),
    sa.Column('skill3', sa.String(length=64), nullable=True),
    sa.Column('fact', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_age'), 'user', ['age'], unique=False)
    op.create_index(op.f('ix_user_bio'), 'user', ['bio'], unique=False)
    op.create_index(op.f('ix_user_fact'), 'user', ['fact'], unique=False)
    op.create_index(op.f('ix_user_skill1'), 'user', ['skill1'], unique=False)
    op.create_index(op.f('ix_user_skill2'), 'user', ['skill2'], unique=False)
    op.create_index(op.f('ix_user_skill3'), 'user', ['skill3'], unique=False)
    op.create_index(op.f('ix_user_university1'), 'user', ['university1'], unique=False)
    op.create_index(op.f('ix_user_university2'), 'user', ['university2'], unique=False)
    op.create_index(op.f('ix_user_user'), 'user', ['user'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user'), table_name='user')
    op.drop_index(op.f('ix_user_university2'), table_name='user')
    op.drop_index(op.f('ix_user_university1'), table_name='user')
    op.drop_index(op.f('ix_user_skill3'), table_name='user')
    op.drop_index(op.f('ix_user_skill2'), table_name='user')
    op.drop_index(op.f('ix_user_skill1'), table_name='user')
    op.drop_index(op.f('ix_user_fact'), table_name='user')
    op.drop_index(op.f('ix_user_bio'), table_name='user')
    op.drop_index(op.f('ix_user_age'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
